// Seed content: 2026 ministry calendar.
// Phase 3 moves this into the Payload `events` collection; until then it is the source of truth.
//
// TODO: confirm with client — the calendar includes private items (Daddy's/Mummy's Retreat at the
// "Private Consecration Center") and the leaders' travel plans ("Traveling ... (Dad and Mum)").
// Confirm these should be published on a public website.

export type EventType =
  | "Services"
  | "Prayer Meetings"
  | "Seminars"
  | "Conferences"
  | "Apostolic Visits"
  | "Retreats";

export interface JomiEvent {
  id: number;
  title: string;
  /** ISO date (YYYY-MM-DD), interpreted in West Africa Time. */
  startDate: string;
  /** ISO date for multi-day events. */
  endDate?: string;
  time: string;
  location: string;
  description: string;
  type: EventType;
  country: string;
  featured?: boolean;
}

export const eventTypes: EventType[] = [
  "Services",
  "Prayer Meetings",
  "Seminars",
  "Conferences",
  "Apostolic Visits",
  "Retreats",
];

export const acronymDefinitions: Record<string, string> = {
  "When (HW) Pray": "When Husbands and Wives Pray",
  JAFOMS: "Jide and Funmi Ojo Mentoring School",
  SOM: "School of Ministry",
  IMRC: "International Ministers’ Refresher Conference",
  GTG: "Grooming the Groom",
  ZBI: "Zoe Bible Institute",
  SDPC: "Spiritual Development & Pastoral Care",
  MOTL: "Men of the Light",
  NRCC: "New Reality Christian Centre",
};

const defaultLocation =
  "The Statement Hotel, 1002 First Ave, Opp. Adamawa Plaza, After Federal High Court, CBD, Abuja";

export const events: JomiEvent[] = [
  {
    id: 1,
    title: "Pregnant Women’s Meeting / Beulah",
    startDate: "2026-01-01",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "A specialized prayer and ministering service for pregnant women and families.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 2,
    title: "Impartation Service",
    startDate: "2026-01-04",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Start the year with powerful apostolic anointing and spiritual impartation.",
    type: "Services",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 3,
    title: "When (HW) Pray (When Husbands and Wives Pray)",
    startDate: "2026-01-05",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Monthly covenant prayer meeting for couples, laying spiritual foundations for families.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 4,
    title: "7 Days of Power (Day 1)",
    startDate: "2026-01-06",
    time: "6:00 PM Daily",
    location: defaultLocation,
    description: "Day 1 of our annual week of prayer, fasting, and spiritual charging.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 5,
    title: "Global Apostolic Midweek Service / 7 Days of Power (Day 2)",
    startDate: "2026-01-07",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek service combined with Day 2 of 7 Days of Power.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 6,
    title: "7 Days of Power (Day 3)",
    startDate: "2026-01-08",
    time: "6:00 PM Daily",
    location: defaultLocation,
    description: "Day 3 of our annual week of prayer, fasting, and spiritual charging.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 7,
    title: "7 Days of Power (Day 4) / GSDC Day 4",
    startDate: "2026-01-09",
    time: "6:00 PM Daily",
    location: defaultLocation,
    description: "Day 4 of 7 Days of Power and GSDC spiritual alignment program.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 8,
    title: "7 Days of Power (Day 5) / GSDC Day 5",
    startDate: "2026-01-10",
    time: "6:00 PM Daily",
    location: defaultLocation,
    description: "Day 5 of 7 Days of Power and GSDC spiritual alignment program.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 9,
    title: "Triumphant Service / 7 Days of Power (Day 6) / GSDC Day 6",
    startDate: "2026-01-11",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Triumphant Service celebrating our victory in Christ.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 10,
    title: "GSDC Day 7",
    startDate: "2026-01-12",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Grand finale of GSDC spiritual alignment program.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 11,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-01-14",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 12,
    title: "Triumphant Service",
    startDate: "2026-01-18",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday celebration of redemptive rights and victory in Christ.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 13,
    title: "When Singles Pray",
    startDate: "2026-01-19",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Specialized prayer session for singles, aligning destinies and relationships.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 14,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-01-21",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 15,
    title: "JAFOMS Orientation (Jide and Funmi Ojo Mentoring School)",
    startDate: "2026-01-23",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Welcome and orientation program for new mentoring students.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 16,
    title: "Friendship Service",
    startDate: "2026-01-25",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "A special service celebrating love, unity, and covenant relationships.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 17,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-01-28",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 18,
    title: "Wives of Sons in Ministry Meeting with Mummy / Daddy’s Retreat",
    startDate: "2026-01-29",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Special mentoring session with Mummy and commencement of Daddy's private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 19,
    title: "Daddy’s Retreat",
    startDate: "2026-01-30",
    endDate: "2026-01-31",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Apostle Jide Ojo's private retreat for consecration and ministerial direction.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 20,
    title: "Impartation Service / Saturate Ekiti",
    startDate: "2026-02-01",
    time: "9:00 AM / 4:00 PM WAT",
    location: "Ado-Ekiti, Ekiti State",
    description: "Sunday Impartation Service combined with the Saturate Ekiti Apostolic Visit.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 21,
    title: "When (HW) Pray (When Husbands and Wives Pray)",
    startDate: "2026-02-02",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Monthly covenant prayer meeting for couples, laying spiritual foundations for families.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 22,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-02-04",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 23,
    title: "Pregnant Women’s Meeting / Beulah",
    startDate: "2026-02-05",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "A specialized prayer and ministering service for pregnant women.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 24,
    title: "Triumphant Service",
    startDate: "2026-02-08",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday celebration of redemptive rights and victory in Christ.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 25,
    title: "Mummy’s Meeting with Pastor Funke",
    startDate: "2026-02-10",
    time: "11:00 AM WAT",
    location: defaultLocation,
    description: "Special ministers and wives mentoring session with Pastor Funmi Ojo and Pastor Funke.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 26,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-02-11",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 27,
    title: "Singles Meet and Mingle",
    startDate: "2026-02-14",
    time: "4:00 PM WAT",
    location: defaultLocation,
    description: "Valentine's Day special gathering for relationship discussions, networking, and fellowship.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 28,
    title: "Triumphant Service",
    startDate: "2026-02-15",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday celebration of redemptive rights and victory in Christ.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 29,
    title: "When Singles Pray",
    startDate: "2026-02-16",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Specialized prayer session for singles, aligning destinies and relationships.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 30,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-02-18",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 31,
    title: "JAFOMS Mentoring Session (Jide and Funmi Ojo Mentoring School)",
    startDate: "2026-02-20",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Active mentoring and leadership training class with Apostle and Pastor Ojo.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 32,
    title: "Friendship Service / Vow Renewal / Lagos Apostolic Meeting",
    startDate: "2026-02-22",
    time: "9:00 AM / 5:00 PM",
    location: "Lagos Center, Nigeria",
    description: "Special service featuring marriage vow renewals, followed by the Lagos Apostolic Meeting.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 33,
    title: "ZBI (Zoe Bible Institute Intensive)",
    startDate: "2026-02-23",
    endDate: "2026-02-26",
    time: "9:00 AM - 3:00 PM Daily",
    location: defaultLocation,
    description: "Rigorous Biblical exposition and ministry training cohort classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 34,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-02-25",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek gathering for deep teaching of the Word and spiritual growth.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 35,
    title: "Wives of Sons in Ministry Meeting with Mummy / Daddy’s Retreat",
    startDate: "2026-02-26",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Monthly spiritual checks and coaching for ministers' wives.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 36,
    title: "Daddy’s Retreat",
    startDate: "2026-02-27",
    endDate: "2026-02-28",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Apostle Jide Ojo's private retreat for consecration and ministerial direction.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 37,
    title: "Worship and Miracle Service",
    startDate: "2026-03-01",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "A supernatural service of deep worship, healings, and miracles.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 38,
    title: "When (HW) Pray",
    startDate: "2026-03-02",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting for husbands and wives.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 39,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-03-04",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 40,
    title: "Pregnant Women’s Meeting / Beulah",
    startDate: "2026-03-05",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayer session.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 41,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-03-08",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday worship service and international protegee mentorship gathering.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 42,
    title: "ZBI Classes",
    startDate: "2026-03-09",
    endDate: "2026-03-12",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Zoe Bible Institute lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 43,
    title: "GTG (Grooming the Groom) / Mummy’s Meeting with Pastor Funke / Global Midweek Service",
    startDate: "2026-03-11",
    time: "10:00 AM / 6:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring classes and midweek service combined.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 44,
    title: "Recalibration",
    startDate: "2026-03-14",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Ministers and leaders alignment seminar.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 45,
    title: "Triumphant Service",
    startDate: "2026-03-15",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 46,
    title: "When Singles Pray",
    startDate: "2026-03-16",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 47,
    title: "Traveling GGC IBADAN (Dad and Mum)",
    startDate: "2026-03-17",
    endDate: "2026-03-21",
    time: "All Day",
    location: "Ibadan, Oyo State",
    description: "Apostle and Pastor Ojo officiating at GGC Ibadan conferences.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 48,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-03-18",
    time: "6:00 PM WAT",
    location: "Ibadan Center / Online",
    description: "Midweek service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 49,
    title: "ZBI Classes",
    startDate: "2026-03-19",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Weekly theological training session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 50,
    title: "JAFOMS Session",
    startDate: "2026-03-20",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship school classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 51,
    title: "Triumphant Service",
    startDate: "2026-03-22",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 52,
    title: "ZBI Classes",
    startDate: "2026-03-23",
    endDate: "2026-03-26",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Zoe Bible Institute Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 53,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-03-24",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Exclusive mentoring for sons in ministry with Apostle Jide Ojo.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 54,
    title: "GTG (Grooming the Groom) / Global Apostolic Midweek Service",
    startDate: "2026-03-25",
    time: "10:00 AM / 6:00 PM WAT",
    location: defaultLocation,
    description: "Grooming session and weekly service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 55,
    title: "Wives of Sons in Ministry Meeting with Mummy",
    startDate: "2026-03-26",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 56,
    title: "Marriage Conference",
    startDate: "2026-03-28",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Base principles of marriage for couples and singles.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 57,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-03-29",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and apostolic regional meeting.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 58,
    title: "ZBI Classes",
    startDate: "2026-03-30",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Intensive training class.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 59,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-03-31",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 60,
    title: "GTG (Grooming the Groom) / Pregnant Women’s Meeting",
    startDate: "2026-04-02",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Combined grooming school session and pregnant women's prayer meeting.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 61,
    title: "Easter Word Feast / Beulah",
    startDate: "2026-04-03",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Day 1 of our Easter Word Feast and Beulah Outreaches.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 62,
    title: "Easter Word Feast",
    startDate: "2026-04-04",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Day 2 of Easter Word Feast; deep scriptural study of resurrection.",
    type: "Conferences",
    country: "Nigeria",
  },
  {
    id: 63,
    title: "Impartation Service",
    startDate: "2026-04-05",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Apostolic Easter celebration and Impartation Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 64,
    title: "When (HW) Pray",
    startDate: "2026-04-06",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting for husbands and wives.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 65,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-04-08",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 66,
    title: "GTG (Grooming the Groom) / Mummy’s Meeting with Pastor Funke / ZBI",
    startDate: "2026-04-09",
    time: "10:00 AM / 2:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring cohort classes and Zoe Bible Institute lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 67,
    title: "Recalibration",
    startDate: "2026-04-11",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Ministers leadership seminar.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 68,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-04-12",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday Service and protegee mentorship session.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 69,
    title: "ZBI Intensive",
    startDate: "2026-04-13",
    endDate: "2026-04-16",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Zoe Bible Institute intensive lecture series.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 70,
    title: "Global Midweek Service / Saturate Akure Apostolic Visit (Ado and Oye)",
    startDate: "2026-04-15",
    time: "6:00 PM WAT",
    location: "Ado & Oye Ekiti / Akure",
    description: "Regional mid-week services and apostolic visitation launch.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 71,
    title: "Saturate Akure Apostolic Visit (Ado and Oye)",
    startDate: "2026-04-18",
    time: "4:00 PM WAT",
    location: "Akure, Ondo State",
    description: "Regional crusade and apostolic power impartation services.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 72,
    title: "Triumphant Service / Apostolic Visit (Ado and Oye)",
    startDate: "2026-04-19",
    time: "9:00 AM / 4:00 PM WAT",
    location: "Akure Center",
    description: "Regional Triumphant service and leadership delegation meetings.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 73,
    title: "When Singles Pray",
    startDate: "2026-04-20",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Spiritual warfare and guidance session for singles.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 74,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-04-21",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Apostolic sonship mentoring and structural guidelines for pastors.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 75,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-04-22",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 76,
    title: "GTG (Grooming the Groom) / ZBI Classes",
    startDate: "2026-04-23",
    time: "10:00 AM / 2:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring and theology classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 77,
    title: "Wives of Sons in Ministry Meeting with Mummy / JAFOMS Session",
    startDate: "2026-04-24",
    time: "10:00 AM / 5:00 PM WAT",
    location: defaultLocation,
    description: "Leadership mentoring and JAFOMS mentoring school classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 78,
    title: "Career and Workplace Summit",
    startDate: "2026-04-25",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Empowering believers with marketplace dominion strategies and career growth principles.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 79,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-04-26",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and regional Lagos meetings.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 80,
    title: "ZBI Intensive",
    startDate: "2026-04-27",
    endDate: "2026-04-30",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Bible lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 81,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-04-29",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 82,
    title: "Daddy’s Retreat / Beulah Outreaches",
    startDate: "2026-05-01",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Apostle Jide Ojo's private retreat combined with Beulah local outreaches.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 83,
    title: "Daddy’s Retreat",
    startDate: "2026-05-02",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 84,
    title: "Impartation Service",
    startDate: "2026-05-03",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Impartation Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 85,
    title: "When (HW) Pray",
    startDate: "2026-05-04",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 86,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-05-06",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 87,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-05-07",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Prayers for mothers and children.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 88,
    title: "Recalibration",
    startDate: "2026-05-09",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Ministers recalibration.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 89,
    title: "ZBI Intensive Classes",
    startDate: "2026-05-10",
    endDate: "2026-05-14",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Zoe Bible Institute lessons.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 90,
    title: "Mummy’s Meeting with Pastor Funke / Global Midweek Service",
    startDate: "2026-05-13",
    time: "11:00 AM / 6:00 PM WAT",
    location: defaultLocation,
    description: "Special session with Pastor Funke and weekly service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 91,
    title: "Saturate Osogbo",
    startDate: "2026-05-15",
    time: "4:00 PM WAT",
    location: "Osogbo, Osun State",
    description: "Regional crusade and apostolic transmission of power.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 92,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-05-10",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday worship and protegees alignment conference.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 93,
    title: "Business Summit",
    startDate: "2026-05-16",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Entrepreneurship training and kingdom wealth systems.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 94,
    title: "ZBI Classes",
    startDate: "2026-05-17",
    endDate: "2026-05-21",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Bible Institute cohort.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 95,
    title: "Triumphant Service",
    startDate: "2026-05-17",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 96,
    title: "When Singles Pray",
    startDate: "2026-05-18",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles covenant prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 97,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-05-20",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 98,
    title: "JAFOMS Classes",
    startDate: "2026-05-22",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring school.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 99,
    title: "Triumphant Service",
    startDate: "2026-05-24",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 100,
    title: "ZBI classes",
    startDate: "2026-05-25",
    endDate: "2026-05-27",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Theology courses.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 101,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-05-26",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 102,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-05-27",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 103,
    title: "IMRC (International Ministers’ Refresher Conference) - Day 1",
    startDate: "2026-05-28",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Global assembly for apostolic recharging, ministry correction, and alignment.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 104,
    title: "IMRC (International Ministers’ Refresher Conference) - Day 2 / Wives of Sons in Ministry with Mummy",
    startDate: "2026-05-29",
    time: "9:00 AM / 2:00 PM WAT",
    location: defaultLocation,
    description: "Day 2 of IMRC alongside the ministers' wives exclusive mentoring session.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 105,
    title: "IMRC (International Ministers’ Refresher Conference) - Day 3",
    startDate: "2026-05-30",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Day 3 and grand finale of IMRC with special anointing and impartation.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 106,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-05-31",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Sunday Friendship service and regional Lagos conference.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 107,
    title: "When (HW) Pray",
    startDate: "2026-06-01",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting for husbands and wives.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 108,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-06-03",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 109,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-06-04",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Prayers for pregnancy.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 110,
    title: "Daddy’s Retreat / Beulah Outreaches",
    startDate: "2026-06-05",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 111,
    title: "Daddy’s Retreat",
    startDate: "2026-06-06",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 112,
    title: "ZBI Intensive Classes",
    startDate: "2026-06-07",
    endDate: "2026-06-11",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Theological lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 113,
    title: "Mummy’s Meeting with Pastor Funke / Global Midweek Service",
    startDate: "2026-06-10",
    time: "11:00 AM / 6:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring session and weekly service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 114,
    title: "Worship and Miracle Service",
    startDate: "2026-06-12",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Supernatural service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 115,
    title: "Recalibration",
    startDate: "2026-06-13",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Leadership calibration.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 116,
    title: "ZBI Cohort",
    startDate: "2026-06-14",
    endDate: "2026-06-18",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 117,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-06-14",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday service and mentorship.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 118,
    title: "When Singles Pray",
    startDate: "2026-06-15",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 119,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-06-17",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 120,
    title: "JAFOMS Session",
    startDate: "2026-06-19",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring school.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 121,
    title: "ZBI Cohort Classes",
    startDate: "2026-06-21",
    endDate: "2026-06-25",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 122,
    title: "Triumphant Service",
    startDate: "2026-06-21",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday worship.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 123,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-06-23",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 124,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-06-24",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 125,
    title: "Fire Up / Women’s Conference",
    startDate: "2026-06-25",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Annual women's gathering for spiritual ignition and destiny alignment.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 126,
    title: "Fire Up / Women’s Conference / Wives of Sons in Ministry with Mummy / Akure Apostolic Visit",
    startDate: "2026-06-26",
    time: "9:00 AM / 4:00 PM WAT",
    location: "Akure, Ondo State",
    description: "Women's conference, ministers' wives cohort, and apostolic visit combined.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 127,
    title: "Akure Apostolic Visit",
    startDate: "2026-06-27",
    time: "4:00 PM WAT",
    location: "Akure, Ondo State",
    description: "Apostolic power crusade in Akure city.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 128,
    title: "Friendship Service / Akure Apostolic Visit",
    startDate: "2026-06-28",
    time: "9:00 AM WAT",
    location: "Akure Center",
    description: "Akure regional Friendship service and covenant declaration.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 129,
    title: "ZBI Classes",
    startDate: "2026-06-28",
    endDate: "2026-06-30",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 130,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-06-30",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 131,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-07-02",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayer session.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 132,
    title: "Daddy’s Retreat / Beulah Outreaches",
    startDate: "2026-07-03",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 133,
    title: "Daddy’s Retreat",
    startDate: "2026-07-04",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 134,
    title: "Mummy’s Meeting with Pastor Funke / ZBI / Global Midweek Service",
    startDate: "2026-07-08",
    time: "11:00 AM / 6:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring, Bible Institute classes, and Midweek service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 135,
    title: "Impartation Service",
    startDate: "2026-07-10",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Mid-year power transmission and impartation service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 136,
    title: "Recalibration",
    startDate: "2026-07-11",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Leaders recalibration.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 137,
    title: "Triumphant Service",
    startDate: "2026-07-12",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 138,
    title: "ZBI Classes",
    startDate: "2026-07-12",
    endDate: "2026-07-16",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Theological cohort classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 139,
    title: "Traveling DOSSOM IBADAN (Dad and Mum)",
    startDate: "2026-07-14",
    endDate: "2026-07-18",
    time: "All Day",
    location: "Ibadan, Oyo State",
    description: "Apostle and Pastor Ojo conducting training and ministration in Ibadan.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 140,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-07-15",
    time: "6:00 PM WAT",
    location: "Ibadan Center / Online",
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 141,
    title: "Ibadan Apostolic Visit",
    startDate: "2026-07-17",
    time: "4:00 PM WAT",
    location: "Ibadan Center, Oyo State",
    description: "Regional crusade and impartation session.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 142,
    title: "International Protegees Meeting / JAFOMS Session",
    startDate: "2026-07-18",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Protege mentorship and JAFOMS classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 143,
    title: "Triumphant Service",
    startDate: "2026-07-19",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 144,
    title: "When Singles Pray",
    startDate: "2026-07-20",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 145,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-07-21",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Pastors mentorship class.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 146,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-07-22",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 147,
    title: "ZBI Classes",
    startDate: "2026-07-23",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 148,
    title: "Ibadan Apostolic Visit / Lagos Apostolic Meeting",
    startDate: "2026-07-24",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Double visitation program in western regional hubs.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 149,
    title: "Parenting Conference",
    startDate: "2026-07-25",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Biblical parenting structures and child development guidelines.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 150,
    title: "Friendship Service",
    startDate: "2026-07-26",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Friendship service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 151,
    title: "Traveling to Ghana for ministration",
    startDate: "2026-07-26",
    endDate: "2026-07-31",
    time: "All Day",
    location: "Accra, Ghana",
    description: "Apostle Jide Ojo ministering at regional conferences in Ghana.",
    type: "Apostolic Visits",
    country: "Ghana",
    featured: true,
  },
  {
    id: 152,
    title: "ZBI Classes",
    startDate: "2026-07-27",
    endDate: "2026-07-30",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 153,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-07-29",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 154,
    title: "Wives of Sons in Ministry Meeting with Mummy / Daddy’s Retreat",
    startDate: "2026-07-30",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session and Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 155,
    title: "Daddy’s Retreat",
    startDate: "2026-07-31",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 156,
    title: "Daddy’s Retreat",
    startDate: "2026-08-01",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 157,
    title: "Impartation Service",
    startDate: "2026-08-02",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 158,
    title: "When (HW) Pray",
    startDate: "2026-08-03",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 159,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-08-05",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 160,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-08-06",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 161,
    title: "Beulah",
    startDate: "2026-08-07",
    time: "4:00 PM WAT",
    location: defaultLocation,
    description: "Specialized prayer session.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 162,
    title: "ZBI Classes",
    startDate: "2026-08-09",
    endDate: "2026-08-13",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Bible Institute cohort.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 163,
    title: "Mummy’s Meeting with Pastor Funke / Global Midweek Service",
    startDate: "2026-08-12",
    time: "11:00 AM / 6:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring session and weekly service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 164,
    title: "Recalibration / Daddy’s Outside Ministration in Oshogbo",
    startDate: "2026-08-14",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Osogbo, Osun State",
    description: "Leaders recalibration combined with city ministration.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 165,
    title: "Oshogbo Apostolic Visit",
    startDate: "2026-08-15",
    time: "4:00 PM WAT",
    location: "Osogbo, Osun State",
    description: "Apostolic power ministration and crusades in Osun region.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 166,
    title: "Triumphant Service / International Protegees Meeting / Oshogbo Apostolic Visit",
    startDate: "2026-08-16",
    time: "9:00 AM / 4:00 PM WAT",
    location: "Osogbo Center",
    description: "Regional triumphant service and mentoring assembly in Oshogbo.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 167,
    title: "ZBI Classes",
    startDate: "2026-08-16",
    endDate: "2026-08-20",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Lectures.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 168,
    title: "When Singles Pray",
    startDate: "2026-08-17",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 169,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-08-19",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 170,
    title: "JAFOMS Session",
    startDate: "2026-08-21",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring school.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 171,
    title: "Triumphant Service",
    startDate: "2026-08-23",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 172,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-08-25",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 173,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-08-26",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 174,
    title: "Wives of Sons in Ministry Meeting with Mummy / Daddy’s Retreat",
    startDate: "2026-08-27",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session and Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 175,
    title: "Singles’ Conference",
    startDate: "2026-08-29",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Empowering singles with vision, relationship tools, and spiritual authority.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 176,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-08-30",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and Lagos regional meeting.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 177,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-09-02",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 178,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-09-03",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 179,
    title: "Daddy’s Retreat / Beulah Outreaches",
    startDate: "2026-09-04",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 180,
    title: "Daddy’s Retreat",
    startDate: "2026-09-05",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 181,
    title: "Worship and Miracle Service",
    startDate: "2026-09-06",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Supernatural service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 182,
    title: "When (HW) Pray",
    startDate: "2026-09-07",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 183,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-09-09",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 184,
    title: "Finished Works Conference",
    startDate: "2026-09-09",
    endDate: "2026-09-12",
    time: "9:00 AM & 5:00 PM Daily",
    location: defaultLocation,
    description: "Our flagship annual conference with our spiritual father, for profound revelations and destines transformation.",
    type: "Conferences",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 185,
    title: "Mummy’s Retreat with Pastor Funke",
    startDate: "2026-09-13",
    endDate: "2026-09-19",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Pastor Funmi Ojo's private retreat with Pastor Funke for spiritual recharging and planning.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 186,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-09-16",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 187,
    title: "Saturate Ibadan",
    startDate: "2026-09-18",
    time: "4:00 PM WAT",
    location: "Ibadan, Oyo State",
    description: "Apostolic power outreach and crusade in Ibadan metropolis.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 188,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-09-20",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday service and mentorship assembly.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 189,
    title: "When Singles Pray",
    startDate: "2026-09-21",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 190,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-09-22",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 191,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-09-23",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 192,
    title: "Wives of Sons in Ministry Meeting with Mummy",
    startDate: "2026-09-24",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 193,
    title: "Triumphant Service",
    startDate: "2026-09-26",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Saturday Special Triumphant Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 194,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-09-27",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and Lagos regional meeting.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 195,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-09-30",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 196,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-10-01",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 197,
    title: "Daddy’s Retreat / Beulah Outreaches",
    startDate: "2026-10-02",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 198,
    title: "Daddy’s Retreat",
    startDate: "2026-10-03",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 199,
    title: "Daddy’s Ministration at Ambassadors of Grace Int Ado-Ekiti",
    startDate: "2026-10-04",
    endDate: "2026-10-08",
    time: "All Day",
    location: "Ado-Ekiti, Ekiti State",
    description: "Apostle Jide Ojo officiating at Ambassadors of Grace international convention.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 200,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-10-07",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 201,
    title: "Mummy’s Meeting with Pastor Funke",
    startDate: "2026-10-08",
    time: "11:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 202,
    title: "Impartation Service",
    startDate: "2026-10-09",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Apostolic power impartation service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 203,
    title: "Recalibration",
    startDate: "2026-10-10",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Ministers leadership calibration.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 204,
    title: "Saturate Abuja",
    startDate: "2026-10-11",
    time: "4:00 PM WAT",
    location: "Abuja National Stadium / Center",
    description: "Massive city-wide apostolic crusade in the capital city, Abuja.",
    type: "Apostolic Visits",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 205,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-10-14",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 206,
    title: "International Protegees Meeting / JAFOMS Session",
    startDate: "2026-10-17",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Protege mentorship and mentoring school classes.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 207,
    title: "Triumphant Service",
    startDate: "2026-10-18",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 208,
    title: "When Singles Pray",
    startDate: "2026-10-19",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 209,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-10-21",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 210,
    title: "Wings of Worship",
    startDate: "2026-10-23",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Night of intensive worship, praise, and prophetic declarations.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 211,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-10-25",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and Lagos regional assembly.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 212,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-10-26",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship class.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 213,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-10-28",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 214,
    title: "Wives of Sons in Ministry Meeting with Mummy / Daddy’s Retreat",
    startDate: "2026-10-29",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session and Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 215,
    title: "Daddy’s Retreat",
    startDate: "2026-10-30",
    endDate: "2026-10-31",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Private retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 216,
    title: "Impartation Service",
    startDate: "2026-11-01",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Impartation Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 217,
    title: "When (HW) Pray",
    startDate: "2026-11-02",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 218,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-11-04",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 219,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-11-05",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 220,
    title: "Beulah",
    startDate: "2026-11-06",
    time: "4:00 PM WAT",
    location: defaultLocation,
    description: "Specialized prayer session.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 221,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-11-11",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 222,
    title: "Mummy’s Meeting with Pastor Funke",
    startDate: "2026-11-12",
    time: "11:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 223,
    title: "Recalibration",
    startDate: "2026-11-14",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Leaders recalibration.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 224,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-11-15",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday service and mentorship assembly.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 225,
    title: "When Singles Pray",
    startDate: "2026-11-16",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 226,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-11-18",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 227,
    title: "JAFOMS Session",
    startDate: "2026-11-20",
    time: "5:00 PM WAT",
    location: defaultLocation,
    description: "Mentoring school.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 228,
    title: "Triumphant Service",
    startDate: "2026-11-22",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 229,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-11-24",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 230,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-11-25",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 231,
    title: "Faith Seminar",
    startDate: "2026-11-26",
    endDate: "2026-11-28",
    time: "9:00 AM Daily",
    location: defaultLocation,
    description: "Interactive seminars unpacking faith principles in the simplest manner.",
    type: "Seminars",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 232,
    title: "Wives of Sons in Ministry Meeting with Mummy",
    startDate: "2026-11-27",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 233,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-11-29",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and Lagos regional assembly.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 234,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-12-02",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 235,
    title: "Pregnant Women’s Meeting",
    startDate: "2026-12-03",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Specialized prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 236,
    title: "Daddy’s Retreat / Beulah Outreaches",
    startDate: "2026-12-04",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 237,
    title: "Daddy’s Retreat",
    startDate: "2026-12-05",
    time: "All Day",
    location: "Private Consecration Center",
    description: "Daddy's retreat.",
    type: "Retreats",
    country: "Nigeria",
  },
  {
    id: 238,
    title: "Worship and Miracle Service",
    startDate: "2026-12-06",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Sunday worship and miracles service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 239,
    title: "When (HW) Pray",
    startDate: "2026-12-07",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Covenant prayer meeting.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 240,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-12-09",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 241,
    title: "Mummy’s Meeting with Pastor Funke",
    startDate: "2026-12-10",
    time: "11:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 242,
    title: "SOM (School of Ministry) Oye-Ekiti",
    startDate: "2026-12-11",
    endDate: "2026-12-12",
    time: "9:00 AM Daily",
    location: "Oye-Ekiti, Ekiti State",
    description: "Intense ministerial training school and leadership development cohort in Oye-Ekiti.",
    type: "Seminars",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 243,
    title: "Triumphant Service / International Protegees Meeting",
    startDate: "2026-12-13",
    time: "9:00 AM / 4:00 PM WAT",
    location: defaultLocation,
    description: "Sunday service and mentorship assembly.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 244,
    title: "Global Apostolic Midweek Service / Carol",
    startDate: "2026-12-16",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Christmas Carol and midweek service combined.",
    type: "Services",
    country: "Nigeria",
    featured: true,
  },
  {
    id: 245,
    title: "Sons in Ministry Meetings with Daddy",
    startDate: "2026-12-20",
    time: "3:00 PM WAT",
    location: defaultLocation,
    description: "Mentorship session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 246,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-12-23",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 247,
    title: "Wives of Sons in Ministry Meeting with Mummy",
    startDate: "2026-12-24",
    time: "10:00 AM WAT",
    location: defaultLocation,
    description: "Mentoring session.",
    type: "Seminars",
    country: "Nigeria",
  },
  {
    id: 248,
    title: "Triumphant Service",
    startDate: "2026-12-26",
    time: "9:00 AM WAT",
    location: defaultLocation,
    description: "Saturday Special Triumphant Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 249,
    title: "When Singles Pray",
    startDate: "2026-12-27",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Singles prayers.",
    type: "Prayer Meetings",
    country: "Nigeria",
  },
  {
    id: 250,
    title: "Global Apostolic Midweek Service",
    startDate: "2026-12-29",
    time: "6:00 PM WAT",
    location: defaultLocation,
    description: "Midweek Service.",
    type: "Services",
    country: "Nigeria",
  },
  {
    id: 251,
    title: "Friendship Service / Lagos Apostolic Meeting",
    startDate: "2026-12-30",
    time: "9:00 AM / 5:00 PM WAT",
    location: "Lagos, Nigeria",
    description: "Friendship service and Lagos regional assembly.",
    type: "Apostolic Visits",
    country: "Nigeria",
  },
  {
    id: 252,
    title: "Bethel (Cross Over Service)",
    startDate: "2026-12-31",
    time: "8:00 PM WAT",
    location: defaultLocation,
    description: "End of year Cross Over Service, entering the new year under power and authority.",
    type: "Prayer Meetings",
    country: "Nigeria",
    featured: true,
  },
];

/** Today's date in Abuja (YYYY-MM-DD), so "upcoming" does not depend on the viewer's timezone. */
export function todayInLagos(): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Africa/Lagos",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
}

/** An event counts as upcoming until the end of its last day. */
export function isUpcoming(event: JomiEvent, today: string): boolean {
  return (event.endDate ?? event.startDate) >= today;
}

export function upcomingEvents(today: string): JomiEvent[] {
  return events.filter((e) => isUpcoming(e, today));
}

export function pastEvents(today: string): JomiEvent[] {
  return events.filter((e) => !isUpcoming(e, today)).reverse();
}

/** e.g. "Sun, 4 Jan 2026" or "30 - 31 Jan 2026" for multi-day events. */
export function formatEventDate(event: JomiEvent): string {
  const opts: Intl.DateTimeFormatOptions = { timeZone: "UTC", day: "numeric", month: "short", year: "numeric" };
  const start = new Date(`${event.startDate}T00:00:00Z`);
  if (!event.endDate) {
    return new Intl.DateTimeFormat("en-GB", { weekday: "short", ...opts }).format(start);
  }
  const end = new Date(`${event.endDate}T00:00:00Z`);
  const startPart = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short" }).format(start);
  return `${startPart} - ${new Intl.DateTimeFormat("en-GB", opts).format(end)}`;
}

/** Expansions for any ministry acronyms appearing in a title. */
export function acronymsIn(title: string): string[] {
  return Object.entries(acronymDefinitions)
    .filter(([acronym]) => title.includes(acronym))
    .map(([acronym, meaning]) => `${acronym}: ${meaning}`);
}
